dist: trusty

cache:
    apt: true

addons:
    apt: 
        packages:
          - texlive-full
          - biber
script:
  - pdflatex -interaction=nonstopmode -halt-on-error *.tex
  - biber *.bcf
  - pdflatex -interaction=nonstopmode -halt-on-error *.tex
  - pdflatex -interaction=nonstopmode -halt-on-error *.tex